# Römork -> +1 -> Aşağıya
# Boşaltma +1-> yıkarıya
# doldurma +1 -> yukarı

# KOVA İÇİN PINLER (HPIO.BOARD)
SAG_DC_MOTOR_PIN = [3, 5, 7]
SOL_DC_MOTOR_PIN = [11, 13, 15]
PIN_STEP_ROMORK = [31, 33, 35, 37]
PIN_STEP_BOSALTMA_CUBUGU = [22, 24, 26, 29]
PIN_STEP_DOLDURMA_CUBUGU = [32, 36, 38, 40]
PIN_SENSOR_CAPRAZ = [8, 10]
PIN_SENSOR_YATAY = [16, 18]
# SERVO_PIN = 12

# DİĞER SABİTLER
KAMERA_COZUNURLUGU = [640, 480]
CV_COZUNURLUGU = [340, 220]
EN_KUCUK_GEMI_PIXEL_ALANI = 250
# Geçici değer yazıldı TODO Sur pixel ölçülecek.
EN_KUCUK_SUR_PIXEL_ALANI = 1500
STEP_MOTOR_BEKLEME_SURESI = 1

# TODO Sabitlerin değerleri ölçülecek
MAX_GEMI_SAYISI = 7
BOSALTMA_SAYISI = 1
DIK_SU_MESAFESI = 26
BANT_TAM_TUR_SAYISI = 6
SENSOR_OLCUMU_KONTROL_SAYISI = 10
MESAFE_YATAY_DUVAR = 40
MESAFE_CAPRAZ_SU = 45
# TODO Steplerin tur sayıları ölçülecek, römork tamam
TUR_SAYISI_ROMORK = 4
TUR_SAYISI_BOSALTMA_CUBUGU = 1.7
TUR_SAYISI_DOLDURMA_CUBUGU = 5

# # BORU İÇİN PINLER (GPIO.BOARD)
# SAG_DC_MOTOR_PIN = [3, 5, 7]
# SOL_DC_MOTOR_PIN = [11, 13, 15]
# PIN_BANT = [31, 33, 35, 37]
# PIN_ON_KOL = [32, 36, 38, 40]
# PIN_SENSOR_CAPRAZ = [8,10]
# PIN_SENSOR_DIKEY = [16,18]
# # SERVO_PIN = 12
